[package]
name = "rust6502"
version = "0.1.0"
authors = ["Nate C-K <nculwell@gmail.com>"]
edition = "2018"

[dependencies]
bitflags = "1.3.2"
num = "0.4.0"
num-derive = "0.3.3"
num-traits = "0.2.15"
sdl2 = "0.35.2"
