#!/usr/bin/python3

import sys

first = True
doc = ''
for line in sys.stdin.readlines():
    ln = line.strip()
    if ln == '':
        continue
    elif line.startswith('     '):
        if first or not (doc[-1].isdigit() and ln[0].isdigit()):
            doc += ' '
    else:
        if first:
            first = False
            doc += ' '
        else:
            doc += '\n'
    doc += ln
print(doc)

